'''
COINAPI Assets
'''

assets = [
{'asset_id': 'BTC', 'name': 'Bitcoin'},
{'asset_id': 'CNY', 'name': 'Yuan Renminbi'},
{'asset_id': 'ETH', 'name': 'Ethereum'},
{'asset_id': 'USD', 'name': 'US Dollar'},
{'asset_id': 'LTC', 'name': 'Litecoin'},
{'asset_id': 'USDT', 'name': 'Tether'},
{'asset_id': 'KRW', 'name': 'Won'},
{'asset_id': 'XRP', 'name': 'Ripple'},
{'asset_id': 'EUR', 'name': 'Euro'},
{'asset_id': 'JPY', 'name': 'Yen'},
{'asset_id': 'BCH', 'name': 'Bitcoin Cash'},
{'asset_id': 'ETC', 'name': 'Ethereum Classic'},
{'asset_id': 'XMR', 'name': 'Monero'},
{'asset_id': 'NEO', 'name': 'NEO'},
{'asset_id': 'EOS', 'name': 'EOS'},
{'asset_id': 'DASH', 'name': 'Dash'},
{'asset_id': 'ZEC', 'name': 'Zcash'},
{'asset_id': 'TRX', 'name': 'TRON'},
{'asset_id': 'BNB', 'name': 'Binance Coin'},
{'asset_id': 'IOTA', 'name': 'MIOTA'},
{'asset_id': 'DOGE', 'name': 'DogeCoin'},
{'asset_id': 'RUB', 'name': 'Russian Ruble'},
{'asset_id': 'QTUM', 'name': 'Qtum'},
{'asset_id': 'XVG', 'name': 'Verge'},
{'asset_id': 'OMG', 'name': 'OmiseGo'},
{'asset_id': 'XLM', 'name': 'Stellar Lumens'},
{'asset_id': 'XEM', 'name': 'NEM'},
{'asset_id': 'ADA', 'name': 'Cardano'},
{'asset_id': 'LSK', 'name': 'Lisk'},
{'asset_id': 'NXT', 'name': 'Nxt'},
{'asset_id': 'VEN', 'name': 'VeChain'},
{'asset_id': 'KST', 'name': 'StarCoin'},
{'asset_id': 'ICX', 'name': 'ICON'},
{'asset_id': 'BCC', 'name': 'BitConnect'},
{'asset_id': 'STRAT', 'name': 'Stratis'},
{'asset_id': 'BTS', 'name': 'BitShares'},
{'asset_id': 'SC', 'name': 'Siacoin'},
{'asset_id': 'DGB', 'name': 'DigiByte'},
{'asset_id': 'BTG', 'name': 'Bitcoin Gold'},
{'asset_id': 'ADX', 'name': 'AdEx'},
{'asset_id': 'WAVES', 'name': 'Waves'},
{'asset_id': 'GNT', 'name': 'Golem'},
{'asset_id': 'SNT', 'name': 'Status'},
{'asset_id': 'HSR', 'name': 'Hshare'},
{'asset_id': 'DGD', 'name': 'DigixDAO'},
{'asset_id': 'REP', 'name': 'Augur'},
{'asset_id': 'AUD', 'name': 'Australian Dollar'},
{'asset_id': 'MAID', 'name': 'MaidSafeCoin'},
{'asset_id': 'ZRX', 'name': '0x'},
{'asset_id': 'IOST', 'name': 'IOStoken'},
{'asset_id': 'NANO', 'name': 'Nano'},
{'asset_id': 'BAT', 'name': 'Basic Attention Toke'},
{'asset_id': 'PPC', 'name': 'Peercoin'},
{'asset_id': 'MCO', 'name': 'Monaco'},
{'asset_id': 'STEEM', 'name': 'Steem'},
{'asset_id': 'CVC', 'name': 'Civic'},
{'asset_id': 'ELF', 'name': 'aelf'},
{'asset_id': 'IDR', 'name': 'Rupiah'},
{'asset_id': 'VTC', 'name': 'Vertcoin'},
{'asset_id': 'PAY', 'name': 'TenX'},
{'asset_id': 'GBP', 'name': 'Pound Sterling'},
{'asset_id': 'POWR', 'name': 'Power Ledger'},
{'asset_id': 'SALT', 'name': 'SALT'},
{'asset_id': 'BCN', 'name': 'Bytecoin'},
{'asset_id': 'EMC2', 'name': 'Einsteinium'},
{'asset_id': 'POE', 'name': 'Po.e'},
{'asset_id': 'CND', 'name': 'Cindicator'},
{'asset_id': 'FCT', 'name': 'Factom'},
{'asset_id': 'STORJ', 'name': 'Storj'},
{'asset_id': 'XDN', 'name': 'DigitalNote'},
{'asset_id': 'ICN', 'name': 'Iconomi'},
{'asset_id': 'MANA', 'name': 'Decentraland'},
{'asset_id': 'RCN', 'name': 'Rcoin'},
{'asset_id': 'FUN', 'name': 'FunFair'},
{'asset_id': 'RDD', 'name': 'Reddcoin'},
{'asset_id': 'SYS', 'name': 'Syscoin'},
{'asset_id': 'ARK', 'name': 'Ark'},
{'asset_id': 'ENG', 'name': 'Enigma'},
{'asset_id': 'NMC', 'name': 'Namecoin'},
{'asset_id': 'GUP', 'name': 'Matchpool'},
{'asset_id': 'WTC', 'name': 'Walton'},
{'asset_id': 'MXN', 'name': 'Mexican Peso'},
{'asset_id': 'ONT', 'name': 'Ontology'},
{'asset_id': 'NAV', 'name': 'NAVCoin'},
{'asset_id': 'BCD', 'name': 'Bitcoin Diamond'},
{'asset_id': 'TNT', 'name': 'Tierion'},
{'asset_id': 'TNB', 'name': 'Time New Ban'},
{'asset_id': 'DNT', 'name': 'district0x'},
{'asset_id': 'BNT', 'name': 'Bancor'},
{'asset_id': 'EDG', 'name': 'Edgeless'},
{'asset_id': 'GAS', 'name': 'Gas'},
{'asset_id': 'LBC', 'name': 'LBRY Credits'},
{'asset_id': 'BCPT', 'name': 'BlockMason'},
{'asset_id': 'NCASH', 'name': 'Nucleus Vision'},
{'asset_id': 'DCR', 'name': 'Decred'},
{'asset_id': 'ARDR', 'name': 'Ardor'},
{'asset_id': 'CAD', 'name': 'Canadian Dollar'},
{'asset_id': 'NEBL', 'name': 'Neblio'},
{'asset_id': 'VIB', 'name': 'Viberate'},
{'asset_id': 'REQ', 'name': 'Request Network'},
{'asset_id': 'GTO', 'name': 'Gifto'},
{'asset_id': 'SRN', 'name': 'SIRIN LABS Toke'},
{'asset_id': 'POT', 'name': 'PotCoin'},
{'asset_id': 'APPC', 'name': 'AppCoins'},
{'asset_id': 'GNO', 'name': 'Gnosis'},
{'asset_id': 'VIA', 'name': 'Viacoin'},
{'asset_id': 'SLL', 'name': 'Leone'},
{'asset_id': 'QSP', 'name': 'Quantstamp'},
{'asset_id': 'LEND', 'name': 'ETHLend'},
{'asset_id': 'KMD', 'name': 'Komodo'},
{'asset_id': 'SNGLS', 'name': 'SingularDTV'},
{'asset_id': 'CTR', 'name': 'Centra'},
{'asset_id': 'BRL', 'name': 'Brazilian Real'},
{'asset_id': 'BLK', 'name': 'BlackCoin'},
{'asset_id': 'LINK', 'name': 'ChainLink'},
{'asset_id': 'XZC', 'name': 'ZCoin'},
{'asset_id': 'LUN', 'name': 'Lunyr'},
{'asset_id': 'UNO', 'name': 'Unobtanium'},
{'asset_id': 'GAME', 'name': 'GameCredits'},
{'asset_id': 'ZIL', 'name': 'Zilliqa'},
{'asset_id': 'WINGS', 'name': 'Wings'},
{'asset_id': 'ZCL', 'name': 'ZClassic'},
{'asset_id': 'CMT', 'name': 'Comet'},
{'asset_id': 'PIVX', 'name': 'PIVX'},
{'asset_id': 'KNC', 'name': 'KingN Coin'},
{'asset_id': 'AST', 'name': 'AirSwap'},
{'asset_id': 'TRIG', 'name': 'Triggers'},
{'asset_id': 'OST', 'name': 'Simple Token'},
{'asset_id': 'QASH', 'name': 'QASH'},
{'asset_id': 'BURST', 'name': 'Burst'},
{'asset_id': 'XTZ', 'name': 'Tezos (Pr'},
{'asset_id': 'BTM', 'name': 'Bytom'},
{'asset_id': 'EMC', 'name': 'Emercoin'},
{'asset_id': 'METAL', 'name': 'MetalCoin'},
{'asset_id': 'ENJ', 'name': 'Enjin Coin'},
{'asset_id': 'HT', 'name': 'Huobi Token'},
{'asset_id': 'EXP', 'name': 'Expanse'},
{'asset_id': 'YOYOW', 'name': 'YOYOW'},
{'asset_id': 'BLZ', 'name': 'BlazeCoin'},
{'asset_id': 'STX', 'name': 'Stox'},
{'asset_id': 'NAS', 'name': 'Nebulas'},
{'asset_id': 'VIBE', 'name': 'VIBE'},
{'asset_id': 'ETN', 'name': 'Electroneum'},
{'asset_id': 'MONA', 'name': 'MonaCoin'},
{'asset_id': 'AMP', 'name': 'Synereo'},
{'asset_id': 'AION', 'name': 'Aion'},
{'asset_id': 'STORM', 'name': 'Storm'},
{'asset_id': 'AIDOC', 'name': 'AI Doctor'},
{'asset_id': 'SUB', 'name': 'Substratum'},
{'asset_id': 'OK', 'name': 'OKCash'},
{'asset_id': 'SAN', 'name': 'Santiment Network Toke'},
{'asset_id': 'NVC', 'name': 'Novacoin'},
{'asset_id': 'DAT', 'name': 'Datum'},
{'asset_id': 'SNM', 'name': 'SONM'},
{'asset_id': 'RLC', 'name': 'iExec RLC'},
{'asset_id': 'EDO', 'name': 'Eidoo'},
{'asset_id': 'PLN', 'name': 'Zloty'},
{'asset_id': 'ITC', 'name': 'IoT Chain'},
{'asset_id': 'OCN', 'name': 'OperaCoin'},
{'asset_id': 'GVT', 'name': 'Genesis Vision'},
{'asset_id': 'ETP', 'name': 'Metaverse ETP'},
{'asset_id': 'LRC', 'name': 'Loopring'},
{'asset_id': 'CDT', 'name': 'CoinDash'},
{'asset_id': 'CLAM', 'name': 'CLAMS'},
{'asset_id': 'SOC', 'name': 'All Sports'},
{'asset_id': 'CHAT', 'name': 'ChatCoin'},
{'asset_id': 'INS', 'name': 'INS Ecosystem'},
{'asset_id': 'EVX', 'name': 'Everex'},
{'asset_id': 'VRC', 'name': 'VeriCoin'},
{'asset_id': 'ETHOS', 'name': 'Ethos'},
{'asset_id': 'PTOY', 'name': 'Patientory'},
{'asset_id': 'RPX', 'name': 'Red Pulse'},
{'asset_id': 'GRS', 'name': 'Groestlcoin'},
{'asset_id': 'RDN', 'name': 'Raiden Network Toke'},
{'asset_id': 'BMC', 'name': 'Blackmoon Crypto'},
{'asset_id': 'THETA', 'name': 'Theta Token'},
{'asset_id': 'DTA', 'name': 'DATA'},
{'asset_id': 'CFI', 'name': 'Cofound.i'},
{'asset_id': 'VOX', 'name': 'Voxels / RevolutionV'},
{'asset_id': 'AE', 'name': 'Aeternity'},
{'asset_id': 'BAY', 'name': 'BitBay'},
{'asset_id': 'RUFF', 'name': 'Ruff'},
{'asset_id': 'NULS', 'name': 'Nuls'},
{'asset_id': 'SMT', 'name': 'SmartMesh'},
{'asset_id': 'SBD', 'name': 'Solomon Islands Dolla'},
{'asset_id': 'FLDC', 'name': 'FoldingCoin'},
{'asset_id': '1ST', 'name': 'FirstBlood'},
{'asset_id': 'PPT', 'name': 'Populous'},
{'asset_id': 'SNC', 'name': 'SunContract'},
{'asset_id': 'UAH', 'name': 'Hryvnia'},
{'asset_id': 'NXS', 'name': 'Nexus'},
{'asset_id': 'RISE', 'name': 'Rise'},
{'asset_id': 'NET', 'name': 'Nimiq'},
{'asset_id': 'ABT', 'name': 'Arcblock'},
{'asset_id': 'ANT', 'name': 'Aragon'},
{'asset_id': 'ELA', 'name': 'Elastos'},
{'asset_id': 'DBC', 'name': 'DeepBrain Chain'},
{'asset_id': 'MTL', 'name': 'Maltese Lira'},
{'asset_id': 'QUN', 'name': 'QunQun'},
{'asset_id': 'ACT', 'name': 'Achain'},
{'asset_id': 'AMB', 'name': 'Ambrosus'},
{'asset_id': 'MDS', 'name': 'MediShares'},
{'asset_id': 'ARN', 'name': 'Aeron'},
{'asset_id': 'XCP', 'name': 'Counterparty'},
{'asset_id': 'ZEN', 'name': 'ZenCash'},
{'asset_id': 'WABI', 'name': 'WaBi'},
{'asset_id': 'GOLD', 'name': 'GOLD'},
{'asset_id': 'TOPC', 'name': 'TopChain'},
{'asset_id': 'FUEL', 'name': 'Etherparty'},
{'asset_id': 'TRST', 'name': 'WeTrust'},
{'asset_id': 'MLN', 'name': 'Melon'},
{'asset_id': 'MYST', 'name': 'Mysterium'},
{'asset_id': 'LET', 'name': 'LinkEye'},
{'asset_id': 'QRL', 'name': 'Quantum Resistant Ledge'},
{'asset_id': 'WAX', 'name': 'WAX'},
{'asset_id': 'MOD', 'name': 'Modum'},
{'asset_id': 'PINK', 'name': 'Pinkcoin'},
{'asset_id': 'UTK', 'name': 'UTRUST'},
{'asset_id': 'SWFTC', 'name': 'SwftCoin'},
{'asset_id': 'BTCD', 'name': 'BitcoinDark'},
{'asset_id': 'DCT', 'name': 'DECENT'},
{'asset_id': 'OAX', 'name': 'OpenAnx'},
{'asset_id': 'ZAR', 'name': 'Rand'},
{'asset_id': 'POA', 'name': 'POA Network'},
{'asset_id': 'BRD', 'name': 'Bread'},
{'asset_id': 'UBQ', 'name': 'Ubiq'},
{'asset_id': 'DLT', 'name': 'Agrello'},
{'asset_id': 'HMQ', 'name': 'Humaniq'},
{'asset_id': 'FLO', 'name': 'Florincoin'},
{'asset_id': 'OMNI', 'name': 'Omni'},
{'asset_id': 'NEOS', 'name': 'Neoscoin'},
{'asset_id': 'GRC', 'name': 'Gridcoin Research'},
{'asset_id': 'FTC', 'name': 'Feathercoin'},
{'asset_id': 'BITB', 'name': 'Bean Cash'},
{'asset_id': 'IOP', 'name': 'Internet of Peopl'},
{'asset_id': 'MTH', 'name': 'Monetha'},
{'asset_id': 'PROPY', 'name': 'Propy token'},
{'asset_id': 'NXC', 'name': 'Nexium'},
{'asset_id': 'MITH', 'name': 'Mithril'},
{'asset_id': 'MEE', 'name': 'CoinMeet'},
{'asset_id': 'ANS', 'name': 'AntShares'},
{'asset_id': 'EKO', 'name': 'EchoLink'},
{'asset_id': 'XPM', 'name': 'Primecoin'},
{'asset_id': 'WPR', 'name': 'WePower'},
{'asset_id': 'RADS', 'name': 'Radium'},
{'asset_id': 'MUSIC', 'name': 'Musicoin'},
{'asset_id': 'DICE', 'name': 'Etheroll'},
{'asset_id': 'IGNIS', 'name': 'Ignis'},
{'asset_id': 'NMR', 'name': 'Numeraire'},
{'asset_id': 'XVC', 'name': 'Vcash'},
{'asset_id': 'YEE', 'name': 'Yee'},
{'asset_id': 'PASC', 'name': 'Pascal Coin'},
{'asset_id': 'MTN', 'name': 'Medicalchain'},
{'asset_id': 'HMP', 'name': 'HempCoin'},
{'asset_id': 'RRT', 'name': 'Bitfinex Recovery Righ'},
{'asset_id': 'GNX', 'name': 'Genaro Network'},
{'asset_id': 'BELA', 'name': 'BelaCoin'},
{'asset_id': 'TRON', 'name': 'TRON'},
{'asset_id': 'TKN', 'name': 'TokenCard'},
{'asset_id': 'IXT', 'name': 'InsureX'},
{'asset_id': 'MTX', 'name': 'Matryx'},
{'asset_id': 'XEL', 'name': 'Elastic'},
{'asset_id': 'XBC', 'name': 'Bond Markets Uni'},
{'asset_id': 'USNBT', 'name': 'NuBits'},
{'asset_id': 'GXS', 'name': 'GXShares'},
{'asset_id': 'EDU', 'name': 'EduCoin'},
{'asset_id': 'CANN', 'name': 'CannabisCoin'},
{'asset_id': 'MSP', 'name': 'Mothership'},
{'asset_id': 'ADT', 'name': 'adToken'},
{'asset_id': 'PRA', 'name': 'ProChain'},
{'asset_id': 'KICK', 'name': 'KickCoin'},
{'asset_id': 'QSH', 'name': 'QSH'},
{'asset_id': 'RIC', 'name': 'Riecoin'},
{'asset_id': 'TIX', 'name': 'Blocktix'},
{'asset_id': 'AIR', 'name': 'AirToken'},
{'asset_id': 'STK', 'name': 'STK'},
{'asset_id': 'R', 'name': 'Revain'},
{'asset_id': 'NZDT', 'name': 'NZDT'},
{'asset_id': 'SLS', 'name': 'SaluS'},
{'asset_id': 'LDC', 'name': 'Leadcoin'},
{'asset_id': 'MDA', 'name': 'Moeda Loyalty Point'},
{'asset_id': 'LINDA', 'name': 'Linda'},
{'asset_id': 'BCY', 'name': 'BitCrystals'},
{'asset_id': 'MEME', 'name': 'MEME'},
{'asset_id': 'THB', 'name': 'Baht'},
{'asset_id': 'CLOAK', 'name': 'CloakCoin'},
{'asset_id': 'PRG', 'name': 'Paragon'},
{'asset_id': 'MUE', 'name': 'MonetaryUnit'},
{'asset_id': 'TIME', 'name': 'Chronobank'},
{'asset_id': 'MGO', 'name': 'MobileGo'},
{'asset_id': 'UNB', 'name': 'UnbreakableCoin'},
{'asset_id': 'ORME', 'name': 'Ormeus Coin'},
{'asset_id': 'ZRC', 'name': 'ZrCoin'},
{'asset_id': 'START', 'name': 'Startcoin'},
{'asset_id': 'SGD', 'name': 'Singapore Dollar'},
{'asset_id': 'SYNX', 'name': 'Syndicate'},
{'asset_id': 'NAUT', 'name': 'Nautiluscoin'},
{'asset_id': 'GBYTE', 'name': 'Byteball'},
{'asset_id': 'XMY', 'name': 'Myriad'},
{'asset_id': 'AVT', 'name': 'Aventus'},
{'asset_id': 'ION', 'name': 'ION'}
        ]